name: Update dependent projects (ALPHA)

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  LIBRARY_NAME: "gisce/commitlint-rules"

jobs:
  update-dependents:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: "gisce/ooui.js"
            branch: "alpha"
          - project: "gisce/react-formiga-table"
            branch: "alpha"
          - project: "gisce/react-ooui"
            branch: "alpha"
          - project: "gisce/powerp.js"
            branch: "alpha"
          - project: "gisce/webclient"
            branch: "alpha"
          - project: "gisce/conscheck"
            branch: "main"
    steps:
      - name: Call Reusable Workflow for Each Project
        uses: gisce/create-update-version-pr@v0.0.5
        with:
          dependentProject: ${{ matrix.project }}
          tagName: ${{ github.event.release.tag_name }}
          dependentProjectBranch: ${{ matrix.branch }}
          libraryName: ${{ env.LIBRARY_NAME }}
          githubToken: ${{ secrets.GH_PAT }}
